### ISSUE TITLE
EKSのアップデート(2020/4/22)に伴う「01_base_resources_cfn.yaml」の修正

### ISSUE THREAD

**Issue by idenpos** [kazusato/k8sbook#1]
■問題
2020/4/22のEKSアップデートに伴い、
書籍上のハンズオン部分が記載通りに進まなくなっている。
https://dev.classmethod.jp/articles/eks-managed-node-group-public-ip-assignment-behavior-is-changed/

■提案
CFnで作成する3つのSubnetの「パブリックIPv4アドレス自動割り当て」を有効化。

**Comment by kazusato** [comment]
どうもありがとうございます。私の方でも、MapPublicIpOnLaunch: trueの付与で手順通り環境構築できることが確認できました。

**Comment by kazusato** [comment]
eksctl 0.19.0（本日時点の最新版）で動作確認できたため、クローズします。
